language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t night91/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true night91/multi-client-test npm test

after_success:
  - docker build -t night91/multi-client ./client
  - docker build -t night91/multi-nginx ./nginx
  - docker build -t night91/multi-server ./server
  - docker build -t night91/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push night91/multi-client
  - docker push night91/multi-nginx
  - docker push night91/multi-server
  - docker push night91/multi-worker

